route:
  receiver: default
  group_by:
    - alertname
    - team
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  routes:
    - matchers:
        - severity="critical"
      receiver: critical

receivers:
  - name: default
  - name: critical
