"""align_document_chunks_chunk_index_nullable

Revision ID: 402be48bec7e
Revises: b3a490b636d1
Create Date: 2026-10-06 07:02:34.711825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '402be48bec7e'
down_revision: Union[str, Sequence[str], None] = 'b3a490b636d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_chunks', 'chunk_index',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_chunks', 'chunk_index',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
