"""add chat embedding provider

Revision ID: d3ba22db292b
Revises: 444652176ea6
Create Date: 2026-08-22 05:12:32.160506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'd3ba22db292b'
down_revision: Union[str, Sequence[str], None] = '444652176ea6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chats", sa.Column("ai_provider", sa.String(), nullable=True))
    op.add_column('chats', sa.Column('ai_model', sa.String(), nullable=True))
    op.add_column('chats', sa.Column('embedding_provider', sa.String(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'embedding_provider')
    op.drop_column('chats', 'ai_model')
    op.drop_column('chats', 'ai_provider')
